version: '3.1'
services:
  flowise:
    image: flowiseai/flowise
    restart: always
    environment:
      - PORT=${PORT:-3000}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME:-user}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD:-password}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE:-myencryptionkey}
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgresql://${POSTGRES_USER:-flowise}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-flowisedb}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-flowise}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-flowisedb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-flowise}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
